p=input("Enter the location of the password file :-")
a=input("Enter what you wannt to add between :-")
l=input("Enter output file name:-")
f=open(l,"w+")
b=open(p,"r")
d=b.read().splitlines()
for i in d:
     f.write(i)
     f.write("\n")
     f.write(a)
     f.write("\n")
f.close()
b.close()
print("done")
print("All mixed password are stored in "+l)
